/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Medico;

import control.COPaciente;
import control.COPacienteExt;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import model.CRUD_Vopacienteext;
import model.Vopaciente;
import model.Vopacienteext;
import view.Secretaria.*;
import view.Login;
import view.TableModelPaciente;

/**
 *
 * @author Maicon Henrique
 */
public class TelaAttPacienteDA extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaAttPacienteDA() {
        initComponents();
        spCirurgias.setVisible(false);
        spAlergias.setVisible(false);
        
    }

    private JTable tbBuscaPaciente = new JTable();
    private JButton SelectPaciente = new JButton();
    private Vopaciente selectedPaciente;
    
    JPopupMenu popup1 = new JPopupMenu();
    
    private TableModelPaciente tbModelPaciente;
    
    private TableModelPaciente getTableModel_NOME(){
        if(tbModelPaciente == null){
            tbModelPaciente = new TableModelPaciente(criaPaciente_NOME());
        }
        return tbModelPaciente;
    }
    
    private List<Vopaciente> criaPaciente_NOME() {
        List<Vopaciente> pacientes = COPaciente.buscaPacientesNome(cmpPaciente.getText());
        return pacientes;
    }
    
    Vopacienteext achou = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFumante = new javax.swing.ButtonGroup();
        bgBebe = new javax.swing.ButtonGroup();
        bgColesterol = new javax.swing.ButtonGroup();
        bgDiabetes = new javax.swing.ButtonGroup();
        bgCirurgias = new javax.swing.ButtonGroup();
        bgAlergias = new javax.swing.ButtonGroup();
        bgDoencasCardiacas = new javax.swing.ButtonGroup();
        txAdicionaPaciente = new javax.swing.JLabel();
        AdicionaPaciente = new javax.swing.JPanel();
        btRemoverPaciente = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        cmpPaciente = new javax.swing.JTextField();
        txNome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txFumante = new javax.swing.JLabel();
        rbFumanteSim = new javax.swing.JRadioButton();
        rbFumanteNao = new javax.swing.JRadioButton();
        txColesterol = new javax.swing.JLabel();
        rbColesterolSim = new javax.swing.JRadioButton();
        rbColesterolNao = new javax.swing.JRadioButton();
        txCirurgias = new javax.swing.JLabel();
        rbcirurgiasSim = new javax.swing.JRadioButton();
        rbCirurgiasNao = new javax.swing.JRadioButton();
        spCirurgias = new javax.swing.JScrollPane();
        taCirurgias = new javax.swing.JTextArea();
        txColesterol1 = new javax.swing.JLabel();
        rbDoencaCardiacaSim = new javax.swing.JRadioButton();
        rbDoencaCardiacaNao = new javax.swing.JRadioButton();
        txCirurgias1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txBebe = new javax.swing.JLabel();
        rbBebeSim = new javax.swing.JRadioButton();
        rbBebeNao = new javax.swing.JRadioButton();
        txDiabetes = new javax.swing.JLabel();
        rbDiabetesSim = new javax.swing.JRadioButton();
        rbDiabetesNao = new javax.swing.JRadioButton();
        txAlegias = new javax.swing.JLabel();
        rbAlergiasSim = new javax.swing.JRadioButton();
        rbAlergiasNao = new javax.swing.JRadioButton();
        spAlergias = new javax.swing.JScrollPane();
        taAlergias = new javax.swing.JTextArea();
        txAlegias1 = new javax.swing.JLabel();
        btBuscaPaciente = new javax.swing.JButton();
        AdicionaPaciente1 = new javax.swing.JPanel();
        txRG = new javax.swing.JLabel();
        cmpRG = new javax.swing.JTextField();
        txCPF = new javax.swing.JLabel();
        cmpCPF = new javax.swing.JTextField();
        txDataNascimento = new javax.swing.JLabel();
        txTelefone = new javax.swing.JLabel();
        cmpTelefone = new javax.swing.JTextField();
        txCelular = new javax.swing.JLabel();
        cmpCelular = new javax.swing.JTextField();
        txEmail = new javax.swing.JLabel();
        cmpEmail = new javax.swing.JTextField();
        txTipoConvenio = new javax.swing.JLabel();
        cbTipoConvenio = new javax.swing.JComboBox();
        txEndereco = new javax.swing.JLabel();
        cmpEndereco = new javax.swing.JTextField();
        dcDataNasc = new com.toedter.calendar.JDateChooser();
        txID = new javax.swing.JLabel();
        cmpID = new javax.swing.JTextField();
        MenuPrincipal = new javax.swing.JMenuBar();
        mnPacientes = new javax.swing.JMenu();
        smnNovoPaciente = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        smnConsultas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnutilitarios = new javax.swing.JMenu();
        smnEnvioEmail = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        smnLogoff = new javax.swing.JMenuItem();
        smnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARS System");

        txAdicionaPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txAdicionaPaciente.setText("Dados do Paciente");

        btRemoverPaciente.setText("Salvar Alterações");
        btRemoverPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverPacienteActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txNome.setText("Nome:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txFumante.setText("Fumante?");

        bgFumante.add(rbFumanteSim);
        rbFumanteSim.setText("Sim");

        bgFumante.add(rbFumanteNao);
        rbFumanteNao.setText("Não");

        txColesterol.setText("Colesterol?");

        bgColesterol.add(rbColesterolSim);
        rbColesterolSim.setText("Sim");

        bgColesterol.add(rbColesterolNao);
        rbColesterolNao.setText("Não");

        txCirurgias.setText("Cirurgias?");

        bgCirurgias.add(rbcirurgiasSim);
        rbcirurgiasSim.setText("Sim");
        rbcirurgiasSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcirurgiasSimActionPerformed(evt);
            }
        });

        bgCirurgias.add(rbCirurgiasNao);
        rbCirurgiasNao.setText("Não");
        rbCirurgiasNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCirurgiasNaoActionPerformed(evt);
            }
        });

        taCirurgias.setColumns(10);
        taCirurgias.setRows(5);
        taCirurgias.setMaximumSize(new java.awt.Dimension(214, 214));
        spCirurgias.setViewportView(taCirurgias);

        txColesterol1.setText("Doenças Cardiacas?");

        bgDoencasCardiacas.add(rbDoencaCardiacaSim);
        rbDoencaCardiacaSim.setText("Sim");

        bgDoencasCardiacas.add(rbDoencaCardiacaNao);
        rbDoencaCardiacaNao.setText("Não");

        txCirurgias1.setText("Quais?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spCirurgias)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFumante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txColesterol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txCirurgias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txCirurgias1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbcirurgiasSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCirurgiasNao))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbColesterolSim)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbColesterolNao))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbFumanteSim)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbFumanteNao)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txColesterol1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDoencaCardiacaSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDoencaCardiacaNao)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFumanteSim)
                    .addComponent(rbFumanteNao)
                    .addComponent(txFumante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbColesterolSim)
                    .addComponent(rbColesterolNao)
                    .addComponent(txColesterol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDoencaCardiacaSim)
                    .addComponent(rbDoencaCardiacaNao)
                    .addComponent(txColesterol1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcirurgiasSim)
                    .addComponent(rbCirurgiasNao)
                    .addComponent(txCirurgias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txCirurgias1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spCirurgias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txBebe.setText("Bebe?");

        bgBebe.add(rbBebeSim);
        rbBebeSim.setText("Sim");

        bgBebe.add(rbBebeNao);
        rbBebeNao.setText("Não");

        txDiabetes.setText("Diabetes?");

        bgDiabetes.add(rbDiabetesSim);
        rbDiabetesSim.setText("Sim");

        bgDiabetes.add(rbDiabetesNao);
        rbDiabetesNao.setText("Não");

        txAlegias.setText("Alergias");

        bgAlergias.add(rbAlergiasSim);
        rbAlergiasSim.setText("Sim");
        rbAlergiasSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlergiasSimActionPerformed(evt);
            }
        });

        bgAlergias.add(rbAlergiasNao);
        rbAlergiasNao.setText("Não");
        rbAlergiasNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlergiasNaoActionPerformed(evt);
            }
        });

        taAlergias.setColumns(10);
        taAlergias.setRows(5);
        spAlergias.setViewportView(taAlergias);

        txAlegias1.setText("Quais?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txDiabetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txAlegias, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txBebe, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txAlegias1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbDiabetesSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbDiabetesNao))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbAlergiasSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAlergiasNao))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rbBebeSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbBebeNao)))
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBebeSim)
                    .addComponent(rbBebeNao)
                    .addComponent(txBebe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDiabetesSim)
                    .addComponent(rbDiabetesNao)
                    .addComponent(txDiabetes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAlergiasSim)
                    .addComponent(rbAlergiasNao)
                    .addComponent(txAlegias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txAlegias1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        btBuscaPaciente.setText("Buscar");
        btBuscaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaPacienteActionPerformed(evt);
            }
        });

        txRG.setText("RG:");

        cmpRG.setEditable(false);

        txCPF.setText("CPF:");

        cmpCPF.setEditable(false);

        txDataNascimento.setText("Data de Nascimento:");

        txTelefone.setText("Telefone:");

        cmpTelefone.setEditable(false);

        txCelular.setText("Celular:");

        cmpCelular.setEditable(false);

        txEmail.setText("E-mail:");

        cmpEmail.setEditable(false);

        txTipoConvenio.setText("Tipo de Convênio:");

        cbTipoConvenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Privado", "Plano de Saúde" }));
        cbTipoConvenio.setEnabled(false);
        cbTipoConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoConvenioActionPerformed(evt);
            }
        });

        txEndereco.setText("Endereço");

        cmpEndereco.setEditable(false);

        dcDataNasc.setEnabled(false);

        javax.swing.GroupLayout AdicionaPaciente1Layout = new javax.swing.GroupLayout(AdicionaPaciente1);
        AdicionaPaciente1.setLayout(AdicionaPaciente1Layout);
        AdicionaPaciente1Layout.setHorizontalGroup(
            AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPaciente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionaPaciente1Layout.createSequentialGroup()
                        .addComponent(txRG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpRG, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(AdicionaPaciente1Layout.createSequentialGroup()
                            .addComponent(txDataNascimento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txTelefone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmpTelefone))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdicionaPaciente1Layout.createSequentialGroup()
                            .addComponent(txEndereco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmpEndereco))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdicionaPaciente1Layout.createSequentialGroup()
                            .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txEmail)
                                .addComponent(txCelular))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(AdicionaPaciente1Layout.createSequentialGroup()
                                    .addComponent(cmpCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(txTipoConvenio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbTipoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmpEmail)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdicionaPaciente1Layout.setVerticalGroup(
            AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPaciente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txRG)
                        .addComponent(cmpRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txCPF)
                        .addComponent(cmpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDataNascimento)
                    .addComponent(dcDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txTelefone)
                        .addComponent(cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCelular)
                    .addComponent(cmpCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTipoConvenio)
                    .addComponent(cbTipoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEndereco)
                    .addComponent(cmpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPaciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEmail)
                    .addComponent(cmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdicionaPacienteLayout = new javax.swing.GroupLayout(AdicionaPaciente);
        AdicionaPaciente.setLayout(AdicionaPacienteLayout);
        AdicionaPacienteLayout.setHorizontalGroup(
            AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdicionaPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AdicionaPaciente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                        .addComponent(txNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmpPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btBuscaPaciente)
                                        .addGap(17, 17, 17)))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdicionaPacienteLayout.createSequentialGroup()
                        .addComponent(btRemoverPaciente)
                        .addGap(313, 313, 313)
                        .addComponent(btCancelar)))
                .addGap(1, 1, 1))
        );
        AdicionaPacienteLayout.setVerticalGroup(
            AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNome)
                    .addComponent(cmpPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdicionaPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRemoverPaciente)
                    .addComponent(btCancelar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        txID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txID.setText("ID:");

        cmpID.setEditable(false);

        mnPacientes.setText("Pacientes");

        smnNovoPaciente.setText("Dados Adicionais");
        smnNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnNovoPacienteActionPerformed(evt);
            }
        });
        mnPacientes.add(smnNovoPaciente);

        MenuPrincipal.add(mnPacientes);

        mnRelatorios.setText("Prontuários");

        smnConsultas.setText("Novo");
        smnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnConsultasActionPerformed(evt);
            }
        });
        mnRelatorios.add(smnConsultas);

        jMenuItem1.setText("Buscar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnRelatorios.add(jMenuItem1);

        MenuPrincipal.add(mnRelatorios);

        mnutilitarios.setText("Relatórios");

        smnEnvioEmail.setText("Receituário");
        smnEnvioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnEnvioEmailActionPerformed(evt);
            }
        });
        mnutilitarios.add(smnEnvioEmail);

        jMenuItem2.setText("Atestado");
        mnutilitarios.add(jMenuItem2);

        jMenuItem3.setText("Declaração de Acomp.");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnutilitarios.add(jMenuItem3);

        jMenuItem4.setText("Atendimentos Efetuados");
        mnutilitarios.add(jMenuItem4);

        MenuPrincipal.add(mnutilitarios);

        mnSistema.setText("Sistema");

        smnLogoff.setText("Logoff");
        smnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnLogoffActionPerformed(evt);
            }
        });
        mnSistema.add(smnLogoff);

        smnSair.setText("Sair");
        smnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSairActionPerformed(evt);
            }
        });
        mnSistema.add(smnSair);

        MenuPrincipal.add(mnSistema);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdicionaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txAdicionaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txAdicionaPaciente)
                    .addComponent(txID)
                    .addComponent(cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AdicionaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_smnSairActionPerformed

    private void smnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnLogoffActionPerformed
       Login TelaLogin = new Login();
       TelaLogin.setLocationRelativeTo(null);
       TelaLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_smnLogoffActionPerformed

    private void smnNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnNovoPacienteActionPerformed
        TelaAttPacienteDA novaTelaPacienteDA = new TelaAttPacienteDA();
        novaTelaPacienteDA.setLocationRelativeTo(null);
        novaTelaPacienteDA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnNovoPacienteActionPerformed

    private void smnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnConsultasActionPerformed
        TelaAddProntuario TelaAddProntuario = new TelaAddProntuario();
        TelaAddProntuario.setLocationRelativeTo(null);
        TelaAddProntuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnConsultasActionPerformed

    private void smnEnvioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnEnvioEmailActionPerformed
        TelaEnvioEmailSMS TelaEnvioMsg = new TelaEnvioEmailSMS();
        TelaEnvioMsg.setLocationRelativeTo(null);
        TelaEnvioMsg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnEnvioEmailActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        TelaMedico TelaMedico = new TelaMedico();
        TelaMedico.setLocationRelativeTo(null);
        TelaMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void rbAlergiasSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlergiasSimActionPerformed
        spAlergias.setVisible(true);
        revalidate();
    }//GEN-LAST:event_rbAlergiasSimActionPerformed

    private void rbAlergiasNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlergiasNaoActionPerformed
        spAlergias.setVisible(false);
        revalidate();
    }//GEN-LAST:event_rbAlergiasNaoActionPerformed

    private void rbCirurgiasNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCirurgiasNaoActionPerformed
        spCirurgias.setVisible(false);
        revalidate();
    }//GEN-LAST:event_rbCirurgiasNaoActionPerformed

    private void rbcirurgiasSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcirurgiasSimActionPerformed
        spCirurgias.setVisible(true);
        revalidate();
    }//GEN-LAST:event_rbcirurgiasSimActionPerformed

    private void btRemoverPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverPacienteActionPerformed
        if (achou == null){
            Vopacienteext ext = new Vopacienteext();
            ext.setPacientePessoaIdPessoa(selectedPaciente.getIdPessoa());
            ext.setBebe(rbBebeSim.isSelected());
            ext.setColesterol(rbColesterolSim.isSelected());
            ext.setDiabetes(rbDiabetesSim.isSelected());
            ext.setDoencasCardiacas(rbDoencaCardiacaSim.isSelected());
            ext.setFuma(rbFumanteSim.isSelected());
            if (rbAlergiasSim.isSelected()){
                ext.setAlergias(taAlergias.getText());
            }
            
            if (rbcirurgiasSim.isSelected()){
                ext.setCirurgias(taCirurgias.getText());
            }
            
            //Salva o novo Paciente ext
            boolean salvou = CRUD_Vopacienteext.salvar(ext);
            if (salvou){
                JOptionPane.showConfirmDialog(rootPane, "Dados Atualizadados com Sucesso!");
            }
        }else{
            achou.setPacientePessoaIdPessoa(selectedPaciente.getIdPessoa());
            achou.setBebe(rbBebeSim.isSelected());
            achou.setColesterol(rbColesterolSim.isSelected());
            achou.setDiabetes(rbDiabetesSim.isSelected());
            achou.setDoencasCardiacas(rbDoencaCardiacaSim.isSelected());
            achou.setFuma(rbFumanteSim.isSelected());
            if (rbAlergiasSim.isSelected()){
                achou.setAlergias(taAlergias.getText());
            }
            
            if (rbcirurgiasSim.isSelected()){
                achou.setCirurgias(taCirurgias.getText());
            }
            boolean salvou = CRUD_Vopacienteext.atualizar(achou);
            if (salvou){
                JOptionPane.showMessageDialog(rootPane, "Dados Atualizadados com Sucesso!");
                TelaMedico novaTela = new TelaMedico();
                novaTela.setLocationRelativeTo(null);
                novaTela.setVisible(true);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_btRemoverPacienteActionPerformed

    private void cbTipoConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoConvenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoConvenioActionPerformed

    private void btSelectPacienteActionPerformed(java.awt.event.ActionEvent evt) {
        int indiceLinha = tbBuscaPaciente.getSelectedRow();
        selectedPaciente = tbModelPaciente.getPaciente(indiceLinha);
        cmpPaciente.setText(selectedPaciente.getNome());
        cmpRG.setText(selectedPaciente.getRg());
        cmpCPF.setText(selectedPaciente.getCpf());
        dcDataNasc.setDate(selectedPaciente.getDataNascimento());
        cmpTelefone.setText(selectedPaciente.getTelefone());
        cmpCelular.setText(selectedPaciente.getCelular());
        if (selectedPaciente.getTipoConvenio().equals("Plano de Saude")){
            cbTipoConvenio.setSelectedIndex(1);
        }else{
            cbTipoConvenio.setSelectedIndex(0);
        }
        cmpEndereco.setText(selectedPaciente.getEndereco());
        cmpEmail.setText(selectedPaciente.getEmail());
        String id = String.valueOf(selectedPaciente.getIdPessoa());
        cmpID.setText(id);
        popup1.setVisible(false);
        
        //Verifica se há dados adicionais(Vopacienteext)
        
        achou = COPacienteExt.buscaPaciente(selectedPaciente.getIdPessoa());
        if(achou != null){
            if(achou.getBebe()){
                rbBebeSim.setSelected(true);
            }else{
                rbBebeNao.setSelected(true);
            }
            
            if(achou.getColesterol()){
                rbColesterolSim.setSelected(true);
            }else{
                rbColesterolNao.setSelected(true);
            }
            
            if(achou.getDiabetes()){
                rbDiabetesSim.setSelected(true);
            }else{
                rbDiabetesNao.setSelected(true);
            }
            
            if(achou.getDoencasCardiacas()){
                rbDoencaCardiacaSim.setSelected(true);
            }else{
                rbDoencaCardiacaNao.setSelected(true);
            }
            
            if(achou.getFuma()){
                rbFumanteSim.setSelected(true);
            }else{
                rbFumanteNao.setSelected(true);
            }
            
            if(achou.getAlergias() != null){
                rbAlergiasSim.setSelected(true);
                taAlergias.setVisible(true);
                taAlergias.setText(achou.getAlergias());
            }
            
            if (achou.getCirurgias() != null){
                rbcirurgiasSim.setSelected(true);
                taCirurgias.setVisible(true);
                taCirurgias.setText(achou.getCirurgias());
            }
        }
    }
    
    private void btBuscaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaPacienteActionPerformed
        tbBuscaPaciente.setModel(getTableModel_NOME());
        tbModelPaciente.limpar();
        tbModelPaciente.addListaDePacientes(criaPaciente_NOME());
        if((tbModelPaciente.getRowCount() == 0) || ("".equals(cmpPaciente.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Paciente não Encontrada!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            tbBuscaPaciente.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbBuscaPaciente.getColumnModel().getColumn(1).setPreferredWidth(250);
            SelectPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectPacienteActionPerformed(evt);
            }
        });
            SelectPaciente.setText("Selecionar");
            popup1.add(tbBuscaPaciente);
            popup1.add(SelectPaciente);
            popup1.show(btBuscaPaciente, 20, 20);
        }
    }//GEN-LAST:event_btBuscaPacienteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaBuscaConsulta TelaBuscaConsulta = new TelaBuscaConsulta();
        TelaBuscaConsulta.setLocationRelativeTo(null);
        TelaBuscaConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAttPacienteDA().setVisible(true);
            }
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdicionaPaciente;
    private javax.swing.JPanel AdicionaPaciente1;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.ButtonGroup bgAlergias;
    private javax.swing.ButtonGroup bgBebe;
    private javax.swing.ButtonGroup bgCirurgias;
    private javax.swing.ButtonGroup bgColesterol;
    private javax.swing.ButtonGroup bgDiabetes;
    private javax.swing.ButtonGroup bgDoencasCardiacas;
    private javax.swing.ButtonGroup bgFumante;
    private javax.swing.JButton btBuscaPaciente;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btRemoverPaciente;
    private javax.swing.JComboBox cbTipoConvenio;
    private javax.swing.JTextField cmpCPF;
    private javax.swing.JTextField cmpCelular;
    private javax.swing.JTextField cmpEmail;
    private javax.swing.JTextField cmpEndereco;
    private javax.swing.JTextField cmpID;
    private javax.swing.JTextField cmpPaciente;
    private javax.swing.JTextField cmpRG;
    private javax.swing.JTextField cmpTelefone;
    private com.toedter.calendar.JDateChooser dcDataNasc;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mnPacientes;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenu mnutilitarios;
    private javax.swing.JRadioButton rbAlergiasNao;
    private javax.swing.JRadioButton rbAlergiasSim;
    private javax.swing.JRadioButton rbBebeNao;
    private javax.swing.JRadioButton rbBebeSim;
    private javax.swing.JRadioButton rbCirurgiasNao;
    private javax.swing.JRadioButton rbColesterolNao;
    private javax.swing.JRadioButton rbColesterolSim;
    private javax.swing.JRadioButton rbDiabetesNao;
    private javax.swing.JRadioButton rbDiabetesSim;
    private javax.swing.JRadioButton rbDoencaCardiacaNao;
    private javax.swing.JRadioButton rbDoencaCardiacaSim;
    private javax.swing.JRadioButton rbFumanteNao;
    private javax.swing.JRadioButton rbFumanteSim;
    private javax.swing.JRadioButton rbcirurgiasSim;
    private javax.swing.JMenuItem smnConsultas;
    private javax.swing.JMenuItem smnEnvioEmail;
    private javax.swing.JMenuItem smnLogoff;
    private javax.swing.JMenuItem smnNovoPaciente;
    private javax.swing.JMenuItem smnSair;
    private javax.swing.JScrollPane spAlergias;
    private javax.swing.JScrollPane spCirurgias;
    private javax.swing.JTextArea taAlergias;
    private javax.swing.JTextArea taCirurgias;
    private javax.swing.JLabel txAdicionaPaciente;
    private javax.swing.JLabel txAlegias;
    private javax.swing.JLabel txAlegias1;
    private javax.swing.JLabel txBebe;
    private javax.swing.JLabel txCPF;
    private javax.swing.JLabel txCelular;
    private javax.swing.JLabel txCirurgias;
    private javax.swing.JLabel txCirurgias1;
    private javax.swing.JLabel txColesterol;
    private javax.swing.JLabel txColesterol1;
    private javax.swing.JLabel txDataNascimento;
    private javax.swing.JLabel txDiabetes;
    private javax.swing.JLabel txEmail;
    private javax.swing.JLabel txEndereco;
    private javax.swing.JLabel txFumante;
    private javax.swing.JLabel txID;
    private javax.swing.JLabel txNome;
    private javax.swing.JLabel txRG;
    private javax.swing.JLabel txTelefone;
    private javax.swing.JLabel txTipoConvenio;
    // End of variables declaration//GEN-END:variables

}
