/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Medico;

import view.Secretaria.*;
import view.Login;

/**
 *
 * @author Maicon Henrique
 */
public class TelaMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnPacientes = new javax.swing.JMenu();
        smnDadosAdicionais = new javax.swing.JMenuItem();
        mnProntuarios = new javax.swing.JMenu();
        smnNovoProntuario = new javax.swing.JMenuItem();
        smnBuscarProntuario = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        smnReceituario = new javax.swing.JMenuItem();
        smnAtestado = new javax.swing.JMenuItem();
        smnDeclaracao = new javax.swing.JMenuItem();
        smnAtendimentoMes = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        smnLogoff = new javax.swing.JMenuItem();
        smnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARS System");

        mnPacientes.setText("Pacientes");

        smnDadosAdicionais.setText("Dados Adicionais");
        smnDadosAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnDadosAdicionaisActionPerformed(evt);
            }
        });
        mnPacientes.add(smnDadosAdicionais);

        jMenuBar1.add(mnPacientes);

        mnProntuarios.setText("Prontuários");

        smnNovoProntuario.setText("Novo");
        smnNovoProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnNovoProntuarioActionPerformed(evt);
            }
        });
        mnProntuarios.add(smnNovoProntuario);

        smnBuscarProntuario.setText("Buscar");
        smnBuscarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBuscarProntuarioActionPerformed(evt);
            }
        });
        mnProntuarios.add(smnBuscarProntuario);

        jMenuBar1.add(mnProntuarios);

        mnRelatorios.setText("Relatórios");

        smnReceituario.setText("Receituário");
        smnReceituario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnReceituarioActionPerformed(evt);
            }
        });
        mnRelatorios.add(smnReceituario);

        smnAtestado.setText("Atestado");
        mnRelatorios.add(smnAtestado);

        smnDeclaracao.setText("Declaração de Acomp.");
        mnRelatorios.add(smnDeclaracao);

        smnAtendimentoMes.setText("Atendimentos Efetuados");
        mnRelatorios.add(smnAtendimentoMes);

        jMenuBar1.add(mnRelatorios);

        mnSistema.setText("Sistema");

        smnLogoff.setText("Logoff");
        smnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnLogoffActionPerformed(evt);
            }
        });
        mnSistema.add(smnLogoff);

        smnSair.setText("Sair");
        smnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSairActionPerformed(evt);
            }
        });
        mnSistema.add(smnSair);

        jMenuBar1.add(mnSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_smnSairActionPerformed

    private void smnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnLogoffActionPerformed
       Login TelaLogin = new Login();
       TelaLogin.setLocationRelativeTo(null);
       TelaLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_smnLogoffActionPerformed

    private void smnDadosAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnDadosAdicionaisActionPerformed
        TelaAttPacienteDA novaTelaPacienteDA = new TelaAttPacienteDA();
        novaTelaPacienteDA.setLocationRelativeTo(null);
        novaTelaPacienteDA.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_smnDadosAdicionaisActionPerformed

    private void smnNovoProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnNovoProntuarioActionPerformed
        TelaAddProntuario TelaAddProntuario = new TelaAddProntuario();
        TelaAddProntuario.setLocationRelativeTo(null);
        TelaAddProntuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnNovoProntuarioActionPerformed

    private void smnBuscarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBuscarProntuarioActionPerformed
        TelaBuscaProntuario TelaBuscaProntuario = new TelaBuscaProntuario();
        TelaBuscaProntuario.setLocationRelativeTo(null);
        TelaBuscaProntuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBuscarProntuarioActionPerformed

    private void smnReceituarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnReceituarioActionPerformed
       
    }//GEN-LAST:event_smnReceituarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaMedico telaMedico = new TelaMedico();
                telaMedico.setLocationRelativeTo(null);
                telaMedico.setVisible(true);
            }
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnPacientes;
    private javax.swing.JMenu mnProntuarios;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenuItem smnAtendimentoMes;
    private javax.swing.JMenuItem smnAtestado;
    private javax.swing.JMenuItem smnBuscarProntuario;
    private javax.swing.JMenuItem smnDadosAdicionais;
    private javax.swing.JMenuItem smnDeclaracao;
    private javax.swing.JMenuItem smnLogoff;
    private javax.swing.JMenuItem smnNovoProntuario;
    private javax.swing.JMenuItem smnReceituario;
    private javax.swing.JMenuItem smnSair;
    // End of variables declaration//GEN-END:variables

}
