/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Medico;

import java.util.List;
import javax.swing.JOptionPane;
import model.CRUD_Voprontuario;
import model.Vopaciente;
import model.Voprontuario;
import view.Secretaria.*;
import view.Login;
import view.TableModelProntuario;

/**
 *
 * @author Maicon Henrique
 */
public class TelaBuscaProntuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaBuscaProntuario() {
        initComponents();
    }
    
    private TableModelProntuario tbModelProntuario;
    

    
    private TableModelProntuario getTableModel(){
        if(tbModelProntuario == null){
            tbModelProntuario = new TableModelProntuario(criaProntuario());
        }
        return tbModelProntuario;
    }
    
    
        private List<Voprontuario> criaProntuario() {
        List<Voprontuario> prontuarios = CRUD_Voprontuario.listar();
        return prontuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBuscaProntuario = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnPacientes = new javax.swing.JMenu();
        smnDadosAdicionais = new javax.swing.JMenuItem();
        mnProntuarios = new javax.swing.JMenu();
        smnNovoProntuario = new javax.swing.JMenuItem();
        smnBuscarProntuario = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        smnReceituario = new javax.swing.JMenuItem();
        smnAtestado = new javax.swing.JMenuItem();
        smnDeclaracao = new javax.swing.JMenuItem();
        smnAtendimentoMes = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        smnLogoff = new javax.swing.JMenuItem();
        smnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARS System");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Prontuário");

        jLabel3.setText("Listar Todos os Prontuários");

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbBuscaProntuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbBuscaProntuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Selecionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        mnPacientes.setText("Pacientes");

        smnDadosAdicionais.setText("Dados Adicionais");
        smnDadosAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnDadosAdicionaisActionPerformed(evt);
            }
        });
        mnPacientes.add(smnDadosAdicionais);

        jMenuBar1.add(mnPacientes);

        mnProntuarios.setText("Prontuários");

        smnNovoProntuario.setText("Novo");
        smnNovoProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnNovoProntuarioActionPerformed(evt);
            }
        });
        mnProntuarios.add(smnNovoProntuario);

        smnBuscarProntuario.setText("Buscar");
        smnBuscarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBuscarProntuarioActionPerformed(evt);
            }
        });
        mnProntuarios.add(smnBuscarProntuario);

        jMenuBar1.add(mnProntuarios);

        mnRelatorios.setText("Relatórios");

        smnReceituario.setText("Receituário");
        smnReceituario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnReceituarioActionPerformed(evt);
            }
        });
        mnRelatorios.add(smnReceituario);

        smnAtestado.setText("Atestado");
        mnRelatorios.add(smnAtestado);

        smnDeclaracao.setText("Declaração de Acomp.");
        mnRelatorios.add(smnDeclaracao);

        smnAtendimentoMes.setText("Atendimentos Efetuados");
        mnRelatorios.add(smnAtendimentoMes);

        jMenuBar1.add(mnRelatorios);

        mnSistema.setText("Sistema");

        smnLogoff.setText("Logoff");
        smnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnLogoffActionPerformed(evt);
            }
        });
        mnSistema.add(smnLogoff);

        smnSair.setText("Sair");
        smnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSairActionPerformed(evt);
            }
        });
        mnSistema.add(smnSair);

        jMenuBar1.add(mnSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_smnSairActionPerformed

    private void smnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnLogoffActionPerformed
       Login TelaLogin = new Login();
       TelaLogin.setLocationRelativeTo(null);
       TelaLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_smnLogoffActionPerformed

    private void smnDadosAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnDadosAdicionaisActionPerformed
        TelaAttPacienteDA novaTelaPacienteDA = new TelaAttPacienteDA();
        novaTelaPacienteDA.setLocationRelativeTo(null);
        novaTelaPacienteDA.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_smnDadosAdicionaisActionPerformed

    private void smnNovoProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnNovoProntuarioActionPerformed
        TelaAddProntuario TelaAddProntuario = new TelaAddProntuario();
        TelaAddProntuario.setLocationRelativeTo(null);
        TelaAddProntuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnNovoProntuarioActionPerformed

    private void smnBuscarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBuscarProntuarioActionPerformed
        TelaBuscaConsulta TelaBuscaConsulta = new TelaBuscaConsulta();
        TelaBuscaConsulta.setLocationRelativeTo(null);
        TelaBuscaConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBuscarProntuarioActionPerformed

    private void smnReceituarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnReceituarioActionPerformed
        TelaConsultasProxDia TelaProxConsultas = new TelaConsultasProxDia();
        TelaProxConsultas.setLocationRelativeTo(null);
        TelaProxConsultas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnReceituarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int indiceLinha = tbBuscaProntuario.getSelectedRow();
        //Verifica Linha Selecionada
        if(indiceLinha != -1){
            Voprontuario selectedPaciente = tbModelProntuario.getProntuario(indiceLinha);
            TelaAttProntuario NovaTelaAttProntuario = new TelaAttProntuario(selectedPaciente);
            NovaTelaAttProntuario.setLocationRelativeTo(null);
            NovaTelaAttProntuario.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione ao menos um Paciente!", "Atenção!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    //Seta o TableModel 
            tbBuscaProntuario.setModel(getTableModel());
            tbModelProntuario.limpar();
            tbModelProntuario.addListaDeProntuarios(criaProntuario());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaMedico TelaMedico = new TelaMedico();
        TelaMedico.setLocationRelativeTo(null);
        TelaMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaBuscaProntuario telaMedico = new TelaBuscaProntuario();
                telaMedico.setLocationRelativeTo(null);
                telaMedico.setVisible(true);
            }
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnPacientes;
    private javax.swing.JMenu mnProntuarios;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenuItem smnAtendimentoMes;
    private javax.swing.JMenuItem smnAtestado;
    private javax.swing.JMenuItem smnBuscarProntuario;
    private javax.swing.JMenuItem smnDadosAdicionais;
    private javax.swing.JMenuItem smnDeclaracao;
    private javax.swing.JMenuItem smnLogoff;
    private javax.swing.JMenuItem smnNovoProntuario;
    private javax.swing.JMenuItem smnReceituario;
    private javax.swing.JMenuItem smnSair;
    private javax.swing.JTable tbBuscaProntuario;
    // End of variables declaration//GEN-END:variables

}
