/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Secretaria;

import control.COPaciente;
import view.Login;

/**
 *
 * @author Maicon Henrique
 */
public class TelaAddPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaAddPaciente() {
        initComponents();
    }

    public void limpaTudo(){
        cmpNome.setText(null);
        cmpRG.setText(null);
        cmpCPF.setText(null);
        dcDataNasc.setDate(null);
        cmpTelefone.setText(null);
        cmpCelular.setText(null);
        cmpEndereco.setText(null);
        cmpEmail.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txAdicionaPaciente = new javax.swing.JLabel();
        AdicionaPaciente = new javax.swing.JPanel();
        txNome = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        txRG = new javax.swing.JLabel();
        cmpRG = new javax.swing.JTextField();
        txCPF = new javax.swing.JLabel();
        cmpCPF = new javax.swing.JTextField();
        txDataNascimento = new javax.swing.JLabel();
        txTelefone = new javax.swing.JLabel();
        cmpTelefone = new javax.swing.JTextField();
        txCelular = new javax.swing.JLabel();
        cmpCelular = new javax.swing.JTextField();
        txEmail = new javax.swing.JLabel();
        cmpEmail = new javax.swing.JTextField();
        txTipoConvenio = new javax.swing.JLabel();
        cbTipoConvenio = new javax.swing.JComboBox();
        btSalvar = new javax.swing.JButton();
        btLimparCampos = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txEndereco = new javax.swing.JLabel();
        cmpEndereco = new javax.swing.JTextField();
        dcDataNasc = new com.toedter.calendar.JDateChooser();
        MenuPrincipal = new javax.swing.JMenuBar();
        mnPacientes = new javax.swing.JMenu();
        smnNovoPaciente = new javax.swing.JMenuItem();
        smnBuscarPaciente = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        smnNovaConsulta = new javax.swing.JMenuItem();
        smnBuscarConsulta = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        smnConsultas = new javax.swing.JMenuItem();
        mnutilitarios = new javax.swing.JMenu();
        smnEnvioEmail = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        smnLogoff = new javax.swing.JMenuItem();
        smnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARS System");

        txAdicionaPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txAdicionaPaciente.setText("Adiciona Paciente");

        txNome.setText("Nome:");

        txRG.setText("RG:");

        txCPF.setText("CPF:");

        txDataNascimento.setText("Data de Nascimento:");

        txTelefone.setText("Telefone:");

        txCelular.setText("Celular:");

        txEmail.setText("E-mail:");

        txTipoConvenio.setText("Tipo de Convênio:");

        cbTipoConvenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Privado", "Plano de Saúde" }));
        cbTipoConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoConvenioActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimparCampos.setText("Limpar Campos");
        btLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txEndereco.setText("Endereço");

        javax.swing.GroupLayout AdicionaPacienteLayout = new javax.swing.GroupLayout(AdicionaPaciente);
        AdicionaPaciente.setLayout(AdicionaPacienteLayout);
        AdicionaPacienteLayout.setHorizontalGroup(
            AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmpNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionaPacienteLayout.createSequentialGroup()
                                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmpRG)
                                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(dcDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmpCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(cmpTelefone)))))
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addComponent(txDataNascimento)
                        .addGap(237, 360, Short.MAX_VALUE))
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txEmail)
                            .addComponent(txCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                .addComponent(btSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btLimparCampos)
                                .addGap(87, 87, 87)
                                .addComponent(btCancelar))
                            .addComponent(cmpEmail)
                            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                .addComponent(cmpCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txTipoConvenio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionaPacienteLayout.createSequentialGroup()
                        .addComponent(txEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpEndereco)))
                .addContainerGap())
        );
        AdicionaPacienteLayout.setVerticalGroup(
            AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNome)
                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txRG)
                    .addComponent(cmpRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCPF)
                    .addComponent(cmpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txDataNascimento)
                        .addComponent(txTelefone)
                        .addComponent(cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCelular)
                    .addComponent(cmpCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTipoConvenio)
                    .addComponent(cbTipoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEndereco)
                    .addComponent(cmpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEmail)
                    .addComponent(cmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimparCampos)
                    .addComponent(btCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnPacientes.setText("Pacientes");

        smnNovoPaciente.setText("Novo");
        smnNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnNovoPacienteActionPerformed(evt);
            }
        });
        mnPacientes.add(smnNovoPaciente);

        smnBuscarPaciente.setText("Buscar");
        smnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBuscarPacienteActionPerformed(evt);
            }
        });
        mnPacientes.add(smnBuscarPaciente);

        MenuPrincipal.add(mnPacientes);

        mnConsultas.setText("Consultas");

        smnNovaConsulta.setText("Nova");
        smnNovaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnNovaConsultaActionPerformed(evt);
            }
        });
        mnConsultas.add(smnNovaConsulta);

        smnBuscarConsulta.setText("Buscar");
        smnBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBuscarConsultaActionPerformed(evt);
            }
        });
        mnConsultas.add(smnBuscarConsulta);

        MenuPrincipal.add(mnConsultas);

        mnRelatorios.setText("Relatórios");

        smnConsultas.setText("Consultas");
        smnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnConsultasActionPerformed(evt);
            }
        });
        mnRelatorios.add(smnConsultas);

        MenuPrincipal.add(mnRelatorios);

        mnutilitarios.setText("Utilitários");
        mnutilitarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutilitariosActionPerformed(evt);
            }
        });

        smnEnvioEmail.setText("Envio de Email/SMS");
        smnEnvioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnEnvioEmailActionPerformed(evt);
            }
        });
        mnutilitarios.add(smnEnvioEmail);

        MenuPrincipal.add(mnutilitarios);

        mnSistema.setText("Sistema");

        smnLogoff.setText("Logoff");
        smnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnLogoffActionPerformed(evt);
            }
        });
        mnSistema.add(smnLogoff);

        smnSair.setText("Sair");
        smnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSairActionPerformed(evt);
            }
        });
        mnSistema.add(smnSair);

        MenuPrincipal.add(mnSistema);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdicionaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txAdicionaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 263, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txAdicionaPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdicionaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_smnSairActionPerformed

    private void smnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnLogoffActionPerformed
       Login TelaLogin = new Login();
       TelaLogin.setLocationRelativeTo(null);
       TelaLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_smnLogoffActionPerformed

    private void smnNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnNovoPacienteActionPerformed
        TelaAddPaciente TelaAddPaciente = new TelaAddPaciente();
        TelaAddPaciente.setLocationRelativeTo(null);
        TelaAddPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnNovoPacienteActionPerformed

    private void smnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBuscarPacienteActionPerformed
        TelaBuscaListaPaciente TelaBusca = new TelaBuscaListaPaciente();
        TelaBusca.setLocationRelativeTo(null);
        TelaBusca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBuscarPacienteActionPerformed

    private void smnNovaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnNovaConsultaActionPerformed
        TelaAddConsulta TelaAddConsulta = new TelaAddConsulta();
        TelaAddConsulta.setLocationRelativeTo(null);
        TelaAddConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnNovaConsultaActionPerformed

    private void smnBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBuscarConsultaActionPerformed
        TelaBuscaConsulta TelaBuscaConsulta = new TelaBuscaConsulta();
        TelaBuscaConsulta.setLocationRelativeTo(null);
        TelaBuscaConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBuscarConsultaActionPerformed

    private void smnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnConsultasActionPerformed
        TelaConsultasProxDia TelaProxConsultas = new TelaConsultasProxDia();
        TelaProxConsultas.setLocationRelativeTo(null);
        TelaProxConsultas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnConsultasActionPerformed

    private void mnutilitariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutilitariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnutilitariosActionPerformed

    private void smnEnvioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnEnvioEmailActionPerformed
        TelaEnvioEmailSMS TelaEnvioMsg = new TelaEnvioEmailSMS();
        TelaEnvioMsg.setLocationRelativeTo(null);
        TelaEnvioMsg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnEnvioEmailActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        TelaSecretaria TelaSecretaria = new TelaSecretaria();
        TelaSecretaria.setLocationRelativeTo(null);
        TelaSecretaria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cbTipoConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoConvenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoConvenioActionPerformed

    private void btLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposActionPerformed
        limpaTudo();
    }//GEN-LAST:event_btLimparCamposActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String tipoPlano;
        int tp = (cbTipoConvenio.getSelectedIndex());
        if(tp == 0){
            tipoPlano = "Privado";            
        }else{
            tipoPlano = "Plano de Saude";
        }
        
        //Chama função de adição na control
            boolean resultado = COPaciente.addPaciente(cmpNome.getText(), cmpRG.getText(), cmpCPF.getText(), 
        dcDataNasc.getDate(), cmpEndereco.getText(), cmpTelefone.getText(), 
            cmpCelular.getText(), cmpEmail.getText(), tipoPlano);
            //Se OK, volta pra tela ADM
            if(resultado){
                TelaSecretaria voltaTela = new TelaSecretaria();
                voltaTela.setLocationRelativeTo(null);
                voltaTela.setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAddPaciente TelaAddPaciente = new TelaAddPaciente();
                TelaAddPaciente.setLocationRelativeTo(null);
                TelaAddPaciente.setVisible(true);
            }
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdicionaPaciente;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btLimparCampos;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbTipoConvenio;
    private javax.swing.JTextField cmpCPF;
    private javax.swing.JTextField cmpCelular;
    private javax.swing.JTextField cmpEmail;
    private javax.swing.JTextField cmpEndereco;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JTextField cmpRG;
    private javax.swing.JTextField cmpTelefone;
    private com.toedter.calendar.JDateChooser dcDataNasc;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnPacientes;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenu mnutilitarios;
    private javax.swing.JMenuItem smnBuscarConsulta;
    private javax.swing.JMenuItem smnBuscarPaciente;
    private javax.swing.JMenuItem smnConsultas;
    private javax.swing.JMenuItem smnEnvioEmail;
    private javax.swing.JMenuItem smnLogoff;
    private javax.swing.JMenuItem smnNovaConsulta;
    private javax.swing.JMenuItem smnNovoPaciente;
    private javax.swing.JMenuItem smnSair;
    private javax.swing.JLabel txAdicionaPaciente;
    private javax.swing.JLabel txCPF;
    private javax.swing.JLabel txCelular;
    private javax.swing.JLabel txDataNascimento;
    private javax.swing.JLabel txEmail;
    private javax.swing.JLabel txEndereco;
    private javax.swing.JLabel txNome;
    private javax.swing.JLabel txRG;
    private javax.swing.JLabel txTelefone;
    private javax.swing.JLabel txTipoConvenio;
    // End of variables declaration//GEN-END:variables

}
