/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Secretaria;

import control.COConsulta;
import control.COMedico;
import control.COPaciente;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import model.Vomedico;
import model.Vopaciente;
import view.Login;
import view.TableModelMedico;
import view.TableModelPaciente;

/**
 *
 * @author Maicon Henrique
 */
public class TelaAddConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaAddConsulta() {
        initComponents();
        
    }

    private JTable tbBuscaPaciente = new JTable();
    private JTable tbBuscaMedico = new JTable();
    private JButton SelectPaciente = new JButton();
    private JButton SelectMedico = new JButton();
    private Vopaciente selectedPaciente;
    private Vomedico selectedMedico;
    
    JPopupMenu popup1 = new JPopupMenu();
    JPopupMenu popup2 = new JPopupMenu();
    
    
    private TableModelPaciente tbModelPaciente;
    private TableModelMedico tbModelMedico;
    
    private TableModelMedico getTableModel_NOME_MED(){
        if(tbModelMedico == null){
            tbModelMedico = new TableModelMedico(criaMedicos_NOME());
        }
        return tbModelMedico;
    }
    
    private TableModelPaciente getTableModel_NOME(){
        if(tbModelPaciente == null){
            tbModelPaciente = new TableModelPaciente(criaPaciente_NOME());
        }
        return tbModelPaciente;
    }
    
    private List<Vomedico> criaMedicos_NOME() {
        List<Vomedico> medicos = COMedico.buscaMedicosNome(cmpMedico.getText());
        return medicos;
    }
    
    private List<Vopaciente> criaPaciente_NOME() {
        List<Vopaciente> pacientes = COPaciente.buscaPacientesNome(cmpPaciente.getText());
        return pacientes;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoConsulta = new javax.swing.ButtonGroup();
        txNovaConsulta = new javax.swing.JLabel();
        NovaConsulta = new javax.swing.JPanel();
        txPaciente = new javax.swing.JLabel();
        cmpPaciente = new javax.swing.JTextField();
        txRG = new javax.swing.JLabel();
        cmpMedico = new javax.swing.JTextField();
        txTipoConsulta = new javax.swing.JLabel();
        btLimparCampos = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btBuscarPaciente = new javax.swing.JButton();
        btBuscarMedico = new javax.swing.JButton();
        rbTipoConsultaNormal = new javax.swing.JRadioButton();
        rbTipoConsultaRetorno = new javax.swing.JRadioButton();
        txDataConsulta = new javax.swing.JLabel();
        txDataConsulta3 = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        cbHorario = new javax.swing.JComboBox();
        txDataConsulta4 = new javax.swing.JLabel();
        dcDataConsulta = new com.toedter.calendar.JDateChooser();
        MenuPrincipal = new javax.swing.JMenuBar();
        mnPacientes = new javax.swing.JMenu();
        smnNovoPaciente = new javax.swing.JMenuItem();
        smnBuscarPaciente = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        smnNovaConsulta = new javax.swing.JMenuItem();
        smnBuscarConsulta = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        smnConsultas = new javax.swing.JMenuItem();
        mnutilitarios = new javax.swing.JMenu();
        smnEnvioEmail = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        smnLogoff = new javax.swing.JMenuItem();
        smnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARS System");

        txNovaConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txNovaConsulta.setText("Nova Consulta");

        txPaciente.setText("Paciente");

        txRG.setText("Médico");

        txTipoConsulta.setText("Tipo de Consulta:");

        btLimparCampos.setText("Limpar Campos");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btBuscarPaciente.setText("Buscar");
        btBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPacienteActionPerformed(evt);
            }
        });

        btBuscarMedico.setText("Buscar");
        btBuscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarMedicoActionPerformed(evt);
            }
        });

        bgTipoConsulta.add(rbTipoConsultaNormal);
        rbTipoConsultaNormal.setText("Normal");

        bgTipoConsulta.add(rbTipoConsultaRetorno);
        rbTipoConsultaRetorno.setText("Retorno");

        txDataConsulta.setText("A Consulta é para o Dia:");

        txDataConsulta3.setText(", às");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:30" }));

        txDataConsulta4.setText("hs.");

        javax.swing.GroupLayout NovaConsultaLayout = new javax.swing.GroupLayout(NovaConsulta);
        NovaConsulta.setLayout(NovaConsultaLayout);
        NovaConsultaLayout.setHorizontalGroup(
            NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NovaConsultaLayout.createSequentialGroup()
                        .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NovaConsultaLayout.createSequentialGroup()
                                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmpMedico)
                                    .addComponent(cmpPaciente)))
                            .addGroup(NovaConsultaLayout.createSequentialGroup()
                                .addComponent(txTipoConsulta)
                                .addGap(30, 30, 30)
                                .addComponent(rbTipoConsultaNormal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbTipoConsultaRetorno)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBuscarPaciente)
                            .addComponent(btBuscarMedico)))
                    .addGroup(NovaConsultaLayout.createSequentialGroup()
                        .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NovaConsultaLayout.createSequentialGroup()
                                .addComponent(btCadastrar)
                                .addGap(72, 72, 72)
                                .addComponent(btLimparCampos))
                            .addGroup(NovaConsultaLayout.createSequentialGroup()
                                .addComponent(txDataConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NovaConsultaLayout.createSequentialGroup()
                                .addComponent(txDataConsulta3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txDataConsulta4)
                                .addGap(0, 39, Short.MAX_VALUE))
                            .addGroup(NovaConsultaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btCancelar)))))
                .addContainerGap())
        );
        NovaConsultaLayout.setVerticalGroup(
            NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPaciente)
                    .addComponent(cmpPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txRG)
                    .addComponent(cmpMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarMedico))
                .addGap(12, 12, 12)
                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTipoConsultaNormal)
                    .addComponent(rbTipoConsultaRetorno)
                    .addComponent(txTipoConsulta))
                .addGap(21, 21, 21)
                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txDataConsulta)
                        .addComponent(txDataConsulta3)
                        .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txDataConsulta4))
                    .addComponent(dcDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(NovaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparCampos)
                    .addComponent(btCancelar)
                    .addComponent(btCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnPacientes.setText("Pacientes");

        smnNovoPaciente.setText("Novo");
        smnNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnNovoPacienteActionPerformed(evt);
            }
        });
        mnPacientes.add(smnNovoPaciente);

        smnBuscarPaciente.setText("Buscar");
        smnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBuscarPacienteActionPerformed(evt);
            }
        });
        mnPacientes.add(smnBuscarPaciente);

        MenuPrincipal.add(mnPacientes);

        mnConsultas.setText("Consultas");

        smnNovaConsulta.setText("Nova");
        smnNovaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnNovaConsultaActionPerformed(evt);
            }
        });
        mnConsultas.add(smnNovaConsulta);

        smnBuscarConsulta.setText("Buscar");
        smnBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBuscarConsultaActionPerformed(evt);
            }
        });
        mnConsultas.add(smnBuscarConsulta);

        MenuPrincipal.add(mnConsultas);

        mnRelatorios.setText("Relatórios");

        smnConsultas.setText("Consultas");
        smnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnConsultasActionPerformed(evt);
            }
        });
        mnRelatorios.add(smnConsultas);

        MenuPrincipal.add(mnRelatorios);

        mnutilitarios.setText("Utilitários");

        smnEnvioEmail.setText("Envio de Email/SMS");
        smnEnvioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnEnvioEmailActionPerformed(evt);
            }
        });
        mnutilitarios.add(smnEnvioEmail);

        MenuPrincipal.add(mnutilitarios);

        mnSistema.setText("Sistema");

        smnLogoff.setText("Logoff");
        smnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnLogoffActionPerformed(evt);
            }
        });
        mnSistema.add(smnLogoff);

        smnSair.setText("Sair");
        smnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSairActionPerformed(evt);
            }
        });
        mnSistema.add(smnSair);

        MenuPrincipal.add(mnSistema);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NovaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txNovaConsulta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txNovaConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NovaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_smnSairActionPerformed

    private void smnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnLogoffActionPerformed
       Login TelaLogin = new Login();
       TelaLogin.setLocationRelativeTo(null);
       TelaLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_smnLogoffActionPerformed

    private void smnNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnNovoPacienteActionPerformed
        TelaAddPaciente TelaAdPaciente = new TelaAddPaciente();
        TelaAdPaciente.setLocationRelativeTo(null);
        TelaAdPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnNovoPacienteActionPerformed

    private void smnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBuscarPacienteActionPerformed
        TelaBuscaListaPaciente TelaBusca = new TelaBuscaListaPaciente();
        TelaBusca.setLocationRelativeTo(null);
        TelaBusca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBuscarPacienteActionPerformed

    private void smnNovaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnNovaConsultaActionPerformed
        TelaAddConsulta TelaAddConsulta = new TelaAddConsulta();
        TelaAddConsulta.setLocationRelativeTo(null);
        TelaAddConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnNovaConsultaActionPerformed

    private void smnBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBuscarConsultaActionPerformed
        TelaBuscaConsulta TelaBuscaConsulta = new TelaBuscaConsulta();
        TelaBuscaConsulta.setLocationRelativeTo(null);
        TelaBuscaConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBuscarConsultaActionPerformed

    private void smnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnConsultasActionPerformed
        TelaConsultasProxDia TelaProxConsultas = new TelaConsultasProxDia();
        TelaProxConsultas.setLocationRelativeTo(null);
        TelaProxConsultas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnConsultasActionPerformed

    private void smnEnvioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnEnvioEmailActionPerformed
        TelaEnvioEmailSMS TelaEnvioMsg = new TelaEnvioEmailSMS();
        TelaEnvioMsg.setLocationRelativeTo(null);
        TelaEnvioMsg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnEnvioEmailActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        TelaSecretaria TelaSecretaria = new TelaSecretaria();
        TelaSecretaria.setLocationRelativeTo(null);
        TelaSecretaria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPacienteActionPerformed
        tbBuscaPaciente.setModel(getTableModel_NOME());
        tbModelPaciente.limpar();
        tbModelPaciente.addListaDePacientes(criaPaciente_NOME());
        if((tbModelPaciente.getRowCount() == 0) || ("".equals(cmpPaciente.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Paciente não Encontrada!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            tbBuscaPaciente.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbBuscaPaciente.getColumnModel().getColumn(1).setPreferredWidth(250);
            SelectPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectPacienteActionPerformed(evt);
            }
        });
            SelectPaciente.setText("Selecionar");
            popup1.add(tbBuscaPaciente);
            popup1.add(SelectPaciente);
            popup1.show(btBuscarPaciente, 20, 20);
        }

    }//GEN-LAST:event_btBuscarPacienteActionPerformed

    private void btBuscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarMedicoActionPerformed
        tbBuscaMedico.setModel(getTableModel_NOME_MED());
        tbModelMedico.limpar();
        tbModelMedico.addListaDeMedicos(criaMedicos_NOME());
        if((tbModelMedico.getRowCount() == 0) || ("".equals(cmpMedico.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Paciente não Encontrada!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            tbBuscaMedico.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbBuscaMedico.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbBuscaMedico.getColumnModel().getColumn(2).setPreferredWidth(250);
            SelectMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectMedicoActionPerformed(evt);
            }
        });
            SelectMedico.setText("Selecionar");
            popup2.add(tbBuscaMedico);
            popup2.add(SelectMedico);
            popup2.show(btBuscarMedico, 20, 20);
        }
    }//GEN-LAST:event_btBuscarMedicoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        int tipoConsulta;
        SimpleDateFormat dataFormatada= new SimpleDateFormat("dd/MM/yyyy"); //você pode usar outras máscaras
        String novaData = new String();
        novaData = dataFormatada.format(dcDataConsulta.getDate());
        if(rbTipoConsultaNormal.isSelected()){
            tipoConsulta = 0;
            boolean saida = COConsulta.addConsulta(selectedMedico, selectedPaciente, 
                    tipoConsulta, novaData, cbHorario.getSelectedIndex());
        }else{
            if(rbTipoConsultaRetorno.isSelected()){
                tipoConsulta = 1;
                boolean saida = COConsulta.addConsulta(selectedMedico, selectedPaciente, 
                        tipoConsulta, novaData, cbHorario.getSelectedIndex());
            }else{
                JOptionPane.showMessageDialog(rootPane, "Selecione o tipo de consulta!", "Atenção!", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btSelectPacienteActionPerformed(java.awt.event.ActionEvent evt) {
        int indiceLinha = tbBuscaPaciente.getSelectedRow();
        selectedPaciente = tbModelPaciente.getPaciente(indiceLinha);
        cmpPaciente.setText(selectedPaciente.getNome());
        popup2.setVisible(false);
    }
    
    private void btSelectMedicoActionPerformed(java.awt.event.ActionEvent evt) {
        int indiceLinha = tbBuscaMedico.getSelectedRow();
        selectedMedico = tbModelMedico.getMedico(indiceLinha);
        cmpMedico.setText(selectedMedico.getNome());
        popup2.setVisible(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddConsulta().setVisible(true);
            }
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JPanel NovaConsulta;
    private javax.swing.ButtonGroup bgTipoConsulta;
    private javax.swing.JButton btBuscarMedico;
    private javax.swing.JButton btBuscarPaciente;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btLimparCampos;
    private javax.swing.JComboBox cbHorario;
    private javax.swing.JTextField cmpMedico;
    private javax.swing.JTextField cmpPaciente;
    private com.toedter.calendar.JDateChooser dcDataConsulta;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnPacientes;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenu mnutilitarios;
    private javax.swing.JRadioButton rbTipoConsultaNormal;
    private javax.swing.JRadioButton rbTipoConsultaRetorno;
    private javax.swing.JMenuItem smnBuscarConsulta;
    private javax.swing.JMenuItem smnBuscarPaciente;
    private javax.swing.JMenuItem smnConsultas;
    private javax.swing.JMenuItem smnEnvioEmail;
    private javax.swing.JMenuItem smnLogoff;
    private javax.swing.JMenuItem smnNovaConsulta;
    private javax.swing.JMenuItem smnNovoPaciente;
    private javax.swing.JMenuItem smnSair;
    private javax.swing.JLabel txDataConsulta;
    private javax.swing.JLabel txDataConsulta3;
    private javax.swing.JLabel txDataConsulta4;
    private javax.swing.JLabel txNovaConsulta;
    private javax.swing.JLabel txPaciente;
    private javax.swing.JLabel txRG;
    private javax.swing.JLabel txTipoConsulta;
    // End of variables declaration//GEN-END:variables

}
