package model;
// Generated 06/06/2013 17:44:05 by Hibernate Tools 3.2.1.GA



/**
 * Voadm generated by hbm2java
 */
public class Voadm  implements java.io.Serializable {


     private int idadm;
     private String username;
     private String senha;

    public Voadm() {
    }

	
    public Voadm(int idadm) {
        this.idadm = idadm;
    }
    public Voadm(int idadm, String username, String senha) {
       this.idadm = idadm;
       this.username = username;
       this.senha = senha;
    }
   
    public int getIdadm() {
        return this.idadm;
    }
    
    public void setIdadm(int idadm) {
        this.idadm = idadm;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


