package model;
// Generated 06/06/2013 17:44:05 by Hibernate Tools 3.2.1.GA

/**
 * Vomedico generated by hbm2java
 */
public class Vomedico extends Vopessoa{

     private int pessoaIdPessoa;
     private String numCrm;
     private String especializacao;
     private String usename;
     private String senha;

    
    public int getPessoaIdPessoa() {
        return this.pessoaIdPessoa;
    }
    
    public void setPessoaIdPessoa(int pessoaIdPessoa) {
        this.pessoaIdPessoa = pessoaIdPessoa;
    }
    
    public String getNumCrm() {
        return this.numCrm;
    }
    
    public void setNumCrm(String numCrm) {
        this.numCrm = numCrm;
    }
    public String getEspecializacao() {
        return this.especializacao;
    }
    
    public void setEspecializacao(String especializacao) {
        this.especializacao = especializacao;
    }
    public String getUsename() {
        return this.usename;
    }
    
    public void setUsename(String usename) {
        this.usename = usename;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

}


