package model;
// Generated 06/06/2013 17:44:05 by Hibernate Tools 3.2.1.GA

/**
 * Vopaciente generated by hbm2java
 */
public class Vopaciente extends Vopessoa{


     private int pessoaIdPessoa;
     private String tipoConvenio;
    public int getPessoaIdPessoa() {
        return this.pessoaIdPessoa;
    }
    
    public void setPessoaIdPessoa(int pessoaIdPessoa) {
        this.pessoaIdPessoa = pessoaIdPessoa;
    }

    public String getTipoConvenio() {
        return this.tipoConvenio;
    }
    
    public void setTipoConvenio(String tipoConvenio) {
        this.tipoConvenio = tipoConvenio;
    }

}


