package model;
// Generated 06/06/2013 17:44:05 by Hibernate Tools 3.2.1.GA



/**
 * Vopacienteext generated by hbm2java
 */
public class Vopacienteext  implements java.io.Serializable {


     private int pacientePessoaIdPessoa;
     private Boolean bebe;
     private Boolean fuma;
     private Boolean colesterol;
     private Boolean diabetes;
     private Boolean doencasCardiacas;
     private String cirurgias;
     private String alergias;

   
   
    public int getPacientePessoaIdPessoa() {
        return this.pacientePessoaIdPessoa;
    }
    
    public void setPacientePessoaIdPessoa(int pacientePessoaIdPessoa) {
        this.pacientePessoaIdPessoa = pacientePessoaIdPessoa;
    }
    
    public Boolean getBebe() {
        return this.bebe;
    }
    
    public void setBebe(Boolean bebe) {
        this.bebe = bebe;
    }
    public Boolean getFuma() {
        return this.fuma;
    }
    
    public void setFuma(Boolean fuma) {
        this.fuma = fuma;
    }
    public Boolean getColesterol() {
        return this.colesterol;
    }
    
    public void setColesterol(Boolean colesterol) {
        this.colesterol = colesterol;
    }
    public Boolean getDiabetes() {
        return this.diabetes;
    }
    
    public void setDiabetes(Boolean diabetes) {
        this.diabetes = diabetes;
    }
    public Boolean getDoencasCardiacas() {
        return this.doencasCardiacas;
    }
    
    public void setDoencasCardiacas(Boolean doencasCardiacas) {
        this.doencasCardiacas = doencasCardiacas;
    }
    public String getCirurgias() {
        return this.cirurgias;
    }
    
    public void setCirurgias(String cirurgias) {
        this.cirurgias = cirurgias;
    }
    public String getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(String alergias) {
        this.alergias = alergias;
    }






}


