package model;
// Generated 06/06/2013 17:44:05 by Hibernate Tools 3.2.1.GA



/**
 * Voprontuario generated by hbm2java
 */
public class Voprontuario {


     private int idProntuario;
     private int vopaciente;
     private int voconsulta;
     private String sintomas;
     private String diagnostico;
     private String tratamento;

    public int getVoconsulta() {
        return voconsulta;
    }

    public void setVoconsulta(int voconsulta) {
        this.voconsulta = voconsulta;
    }

    
     
     public int getIdProntuario() {
        return idProntuario;
    }

    public void setIdProntuario(int idProntuario) {
        this.idProntuario = idProntuario;
    }

    public int getVopaciente() {
        return vopaciente;
    }

    public void setVopaciente(int vopaciente) {
        this.vopaciente = vopaciente;
    }

    public String getSintomas() {
        return sintomas;
    }

    public void setSintomas(String sintomas) {
        this.sintomas = sintomas;
    }

    public String getDiagnostico() {
        return diagnostico;
    }

    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }

    public String getTratamento() {
        return tratamento;
    }

    public void setTratamento(String tratamento) {
        this.tratamento = tratamento;
    }


}


