package model;
// Generated 06/06/2013 17:44:05 by Hibernate Tools 3.2.1.GA



/**
 * Vosecretaria generated by hbm2java
 */
public class Vosecretaria  extends Vopessoa{


     private int pessoaIdPessoa;
     private Integer salario;
     private String username;
     private String senha;

    
   
    public int getPessoaIdPessoa() {
        return this.pessoaIdPessoa;
    }
    
    public void setPessoaIdPessoa(int pessoaIdPessoa) {
        this.pessoaIdPessoa = pessoaIdPessoa;
    }
    
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    
}


