/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package view.adm;

import view.Secretaria.*;
import view.Login;

/**
 *
 * @author Maicon Henrique
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JMenuBar();
        mnCadastrar = new javax.swing.JMenu();
        smnMedico = new javax.swing.JMenuItem();
        smnSecretaria = new javax.swing.JMenuItem();
        mnBuscar = new javax.swing.JMenu();
        smnBCadastro = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        smnLogoff = new javax.swing.JMenuItem();
        smnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARS System");

        mnCadastrar.setText("Cadastrar");

        smnMedico.setText("Médico");
        smnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnMedicoActionPerformed(evt);
            }
        });
        mnCadastrar.add(smnMedico);

        smnSecretaria.setText("Secretária");
        smnSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSecretariaActionPerformed(evt);
            }
        });
        mnCadastrar.add(smnSecretaria);

        MenuPrincipal.add(mnCadastrar);

        mnBuscar.setText("Buscar");

        smnBCadastro.setText("Cadastro");
        smnBCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBCadastroActionPerformed(evt);
            }
        });
        mnBuscar.add(smnBCadastro);

        MenuPrincipal.add(mnBuscar);

        mnSistema.setText("Sistema");

        smnLogoff.setText("Logoff");
        smnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnLogoffActionPerformed(evt);
            }
        });
        mnSistema.add(smnLogoff);

        smnSair.setText("Sair");
        smnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSairActionPerformed(evt);
            }
        });
        mnSistema.add(smnSair);

        MenuPrincipal.add(mnSistema);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_smnSairActionPerformed

    private void smnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnLogoffActionPerformed
       Login TelaLogin = new Login();
       TelaLogin.setLocationRelativeTo(null);
       TelaLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_smnLogoffActionPerformed

    private void smnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnMedicoActionPerformed
        TelaAddMedico TelaAddMedico = new TelaAddMedico();
        TelaAddMedico.setLocationRelativeTo(null);
        TelaAddMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnMedicoActionPerformed

    private void smnSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSecretariaActionPerformed
        TelaAddSecretaria TelaAddSec = new TelaAddSecretaria();
        TelaAddSec.setLocationRelativeTo(null);
        TelaAddSec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnSecretariaActionPerformed

    private void smnBCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBCadastroActionPerformed
        TelaBuscaRetornaPessoa TelaBuscaPessoa = new TelaBuscaRetornaPessoa();
        TelaBuscaPessoa.setLocationRelativeTo(null);
        TelaBuscaPessoa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAdm TelaAdm = new TelaAdm();
                TelaAdm.setLocationRelativeTo(null);
                TelaAdm.setVisible(true);
            }
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu mnBuscar;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenuItem smnBCadastro;
    private javax.swing.JMenuItem smnLogoff;
    private javax.swing.JMenuItem smnMedico;
    private javax.swing.JMenuItem smnSair;
    private javax.swing.JMenuItem smnSecretaria;
    // End of variables declaration//GEN-END:variables

}
