/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package view.adm;

import control.COMedico;
import javax.swing.JOptionPane;
import model.Vomedico;
import view.Secretaria.*;
import view.Login;

/**
 *
 * @author Maicon Henrique
 */
public class TelaAttMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaSecretaria
     */
    public TelaAttMedico(Vomedico medico) {
        initComponents();
        //Atualiza os campos com o Objeto Médico passado por parametro
        cmpNome.setText(medico.getNome());
        cmpRG.setText(medico.getRg());
        cmpCPF.setText(medico.getCpf());
        dcDataNasc.setDate(medico.getDataNascimento());
        cmpTelefone.setText(medico.getTelefone());
        cmpCelular.setText(medico.getCelular());
        cmpNCrm.setText(medico.getNumCrm());
        cmpEndereco.setText(medico.getEndereco());
        cmpEmail.setText(medico.getEmail());
        cmpEspecializacao.setText(medico.getEspecializacao());
        cmpLogin.setText(medico.getUsename());
        String id = String.valueOf(medico.getIdPessoa());
        cmpID.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txAdicionaPaciente = new javax.swing.JLabel();
        AdicionaPaciente = new javax.swing.JPanel();
        txNome = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        txRG = new javax.swing.JLabel();
        cmpRG = new javax.swing.JTextField();
        txCPF = new javax.swing.JLabel();
        cmpCPF = new javax.swing.JTextField();
        txDataNascimento = new javax.swing.JLabel();
        txTelefone = new javax.swing.JLabel();
        cmpTelefone = new javax.swing.JTextField();
        txCelular = new javax.swing.JLabel();
        cmpCelular = new javax.swing.JTextField();
        txEmail = new javax.swing.JLabel();
        cmpEmail = new javax.swing.JTextField();
        txNumCRM = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btExcluirMedico = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        cmpNCrm = new javax.swing.JTextField();
        txLogin = new javax.swing.JLabel();
        cmpLogin = new javax.swing.JTextField();
        txSenha = new javax.swing.JLabel();
        txRepitaSenha = new javax.swing.JLabel();
        txEspecializacao = new javax.swing.JLabel();
        cmpEspecializacao = new javax.swing.JTextField();
        dcDataNasc = new com.toedter.calendar.JDateChooser();
        pfSenha = new javax.swing.JPasswordField();
        pfRepitaSenha = new javax.swing.JPasswordField();
        txEndereco = new javax.swing.JLabel();
        cmpEndereco = new javax.swing.JTextField();
        txID = new javax.swing.JLabel();
        cmpID = new javax.swing.JTextField();
        MenuPrincipal = new javax.swing.JMenuBar();
        mnCadastrar = new javax.swing.JMenu();
        smnMedico = new javax.swing.JMenuItem();
        smnSecretaria = new javax.swing.JMenuItem();
        mnBuscar = new javax.swing.JMenu();
        smnBCadastro = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();
        smnLogoff = new javax.swing.JMenuItem();
        smnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARS System");

        txAdicionaPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txAdicionaPaciente.setText("Médico");

        txNome.setText("Nome:");

        txRG.setText("RG:");

        txCPF.setText("CPF:");

        txDataNascimento.setText("Data de Nascimento:");

        txTelefone.setText("Telefone:");

        txCelular.setText("Celular:");

        txEmail.setText("E-mail:");

        txNumCRM.setText("Nº CRM:");

        btSalvar.setText("Salvar Alterações");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluirMedico.setText("Excluir Médico");
        btExcluirMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirMedicoActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txLogin.setText("Login:");

        txSenha.setText("Senha:");

        txRepitaSenha.setText("Repita a Senha:");

        txEspecializacao.setText("Especialização:");

        txEndereco.setText("Endereço");

        javax.swing.GroupLayout AdicionaPacienteLayout = new javax.swing.GroupLayout(AdicionaPaciente);
        AdicionaPaciente.setLayout(AdicionaPacienteLayout);
        AdicionaPacienteLayout.setHorizontalGroup(
            AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmpNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionaPacienteLayout.createSequentialGroup()
                                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmpRG)
                                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(dcDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmpCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(cmpTelefone)))))
                    .addComponent(txDataNascimento)
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txEmail)
                            .addComponent(txCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmpEmail)
                            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                .addComponent(cmpCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txNumCRM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmpNCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                .addComponent(btSalvar)
                                .addGap(101, 101, 101)
                                .addComponent(btExcluirMedico)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdicionaPacienteLayout.createSequentialGroup()
                                .addComponent(txLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txRepitaSenha)))
                        .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(btCancelar))
                            .addComponent(pfRepitaSenha)))
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addComponent(txEspecializacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpEspecializacao))
                    .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                        .addComponent(txEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpEndereco)))
                .addContainerGap())
        );
        AdicionaPacienteLayout.setVerticalGroup(
            AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionaPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNome)
                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txRG)
                    .addComponent(cmpRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCPF)
                    .addComponent(cmpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txDataNascimento)
                        .addComponent(txTelefone)
                        .addComponent(cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCelular)
                    .addComponent(cmpCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNumCRM)
                    .addComponent(cmpNCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEmail)
                    .addComponent(cmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEndereco)
                    .addComponent(cmpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEspecializacao)
                    .addComponent(cmpEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLogin)
                    .addComponent(cmpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txSenha)
                    .addComponent(txRepitaSenha)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfRepitaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdicionaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btExcluirMedico)
                    .addComponent(btCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txID.setText("ID:");

        cmpID.setEditable(false);

        mnCadastrar.setText("Cadastrar");

        smnMedico.setText("Médico");
        smnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnMedicoActionPerformed(evt);
            }
        });
        mnCadastrar.add(smnMedico);

        smnSecretaria.setText("Secretária");
        smnSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSecretariaActionPerformed(evt);
            }
        });
        mnCadastrar.add(smnSecretaria);

        MenuPrincipal.add(mnCadastrar);

        mnBuscar.setText("Buscar");

        smnBCadastro.setText("Cadastro");
        smnBCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnBCadastroActionPerformed(evt);
            }
        });
        mnBuscar.add(smnBCadastro);

        MenuPrincipal.add(mnBuscar);

        mnSistema.setText("Sistema");

        smnLogoff.setText("Logoff");
        smnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnLogoffActionPerformed(evt);
            }
        });
        mnSistema.add(smnLogoff);

        smnSair.setText("Sair");
        smnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSairActionPerformed(evt);
            }
        });
        mnSistema.add(smnSair);

        MenuPrincipal.add(mnSistema);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdicionaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txAdicionaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txAdicionaPaciente)
                    .addComponent(txID)
                    .addComponent(cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdicionaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_smnSairActionPerformed

    private void smnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnLogoffActionPerformed
       Login TelaLogin = new Login();
       TelaLogin.setLocationRelativeTo(null);
       TelaLogin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_smnLogoffActionPerformed

    private void smnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnMedicoActionPerformed
        TelaAddMedico TelaAddMedico = new TelaAddMedico();
        TelaAddMedico.setLocationRelativeTo(null);
        TelaAddMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnMedicoActionPerformed

    private void smnSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSecretariaActionPerformed
        TelaAddSecretaria TelaAddSec = new TelaAddSecretaria();
        TelaAddSec.setLocationRelativeTo(null);
        TelaAddSec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnSecretariaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        TelaAdm VoltaTela = new TelaAdm();
        VoltaTela.setLocationRelativeTo(null);
        VoltaTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void smnBCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnBCadastroActionPerformed
        TelaBuscaRetornaPessoa TelaBuscaPessoa = new TelaBuscaRetornaPessoa();
        TelaBuscaPessoa.setLocationRelativeTo(null);
        TelaBuscaPessoa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_smnBCadastroActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        //Confere senhas iguais
        String senha1 = new String(pfSenha.getPassword());
        String senha2 = new String(pfRepitaSenha.getPassword());
        if(senha1.equals(senha2)){
            //Chama função de adição na control
            int id = Integer.parseInt(cmpID.getText());
            boolean resultado = COMedico.attMedico(id,cmpNome.getText(), cmpRG.getText(), cmpCPF.getText(), 
            dcDataNasc.getDate(), cmpEndereco.getText(), cmpTelefone.getText(), 
            cmpCelular.getText(), cmpEmail.getText(), cmpNCrm.getText(), 
            cmpEspecializacao.getText(), cmpLogin.getText(), senha1);
            //Se OK, volta pra tela ADM
            if(resultado){
                TelaAdm voltaTela = new TelaAdm();
                voltaTela.setLocationRelativeTo(null);
                voltaTela.setVisible(true);
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "As senhas não conferem!");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirMedicoActionPerformed
        int id = Integer.parseInt(cmpID.getText());
        int result = JOptionPane.showConfirmDialog(rootPane, "Tem Certeza que deseja remover este médico?");
        if(result == 0){
            boolean resultado = COMedico.excluiMedico(id);
            if(resultado){
                TelaAdm voltaTela = new TelaAdm();
                voltaTela.setLocationRelativeTo(null);
                voltaTela.setVisible(true);
                this.dispose();
            }
        }
        
        
        
    }//GEN-LAST:event_btExcluirMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAddPaciente TelaAddPaciente = new TelaAddPaciente();
                TelaAddPaciente.setLocationRelativeTo(null);
                TelaAddPaciente.setVisible(true);
            }
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdicionaPaciente;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluirMedico;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField cmpCPF;
    private javax.swing.JTextField cmpCelular;
    private javax.swing.JTextField cmpEmail;
    private javax.swing.JTextField cmpEndereco;
    private javax.swing.JTextField cmpEspecializacao;
    private javax.swing.JTextField cmpID;
    private javax.swing.JTextField cmpLogin;
    private javax.swing.JTextField cmpNCrm;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JTextField cmpRG;
    private javax.swing.JTextField cmpTelefone;
    private com.toedter.calendar.JDateChooser dcDataNasc;
    private javax.swing.JMenu mnBuscar;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JPasswordField pfRepitaSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JMenuItem smnBCadastro;
    private javax.swing.JMenuItem smnLogoff;
    private javax.swing.JMenuItem smnMedico;
    private javax.swing.JMenuItem smnSair;
    private javax.swing.JMenuItem smnSecretaria;
    private javax.swing.JLabel txAdicionaPaciente;
    private javax.swing.JLabel txCPF;
    private javax.swing.JLabel txCelular;
    private javax.swing.JLabel txDataNascimento;
    private javax.swing.JLabel txEmail;
    private javax.swing.JLabel txEndereco;
    private javax.swing.JLabel txEspecializacao;
    private javax.swing.JLabel txID;
    private javax.swing.JLabel txLogin;
    private javax.swing.JLabel txNome;
    private javax.swing.JLabel txNumCRM;
    private javax.swing.JLabel txRG;
    private javax.swing.JLabel txRepitaSenha;
    private javax.swing.JLabel txSenha;
    private javax.swing.JLabel txTelefone;
    // End of variables declaration//GEN-END:variables

}
